/**
 * Email Service
 * Handles sending automated meeting recap emails
 */

import nodemailer from 'nodemailer';
import { logger } from '../utils/logger';

export interface MeetingEmailPayload {
  to: string;
  meetingTitle: string;
  date: string;
  summary: string;
  keyDetails: string[];
  transcript: string;
}

/**
 * Initialize nodemailer transporter
 */
function createTransporter() {
  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = parseInt(process.env.SMTP_PORT || '587');
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;
  const smtpFrom = process.env.SMTP_FROM || smtpUser;

  if (!smtpHost || !smtpUser || !smtpPass) {
    throw new Error('SMTP configuration incomplete. Please set SMTP_HOST, SMTP_USER, and SMTP_PASS in .env');
  }

  return nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465, // true for 465, false for other ports
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });
}

/**
 * Generate HTML email body for meeting recap
 */
function generateEmailHTML(payload: MeetingEmailPayload): string {
  const keyDetailsHTML = payload.keyDetails.length > 0
    ? `
      <ul style="margin: 16px 0; padding-left: 24px; color: #374151;">
        ${payload.keyDetails.map(detail => `<li style="margin: 8px 0;">${detail}</li>`).join('')}
      </ul>
    `
    : '<p style="color: #6B7280; font-style: italic;">No specific details available.</p>';

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Meeting Recap: ${payload.meetingTitle}</title>
      </head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #111827; background-color: #F9FAFB; margin: 0; padding: 0;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #FFFFFF; padding: 32px;">
          <!-- Header -->
          <div style="border-bottom: 2px solid #DC2626; padding-bottom: 16px; margin-bottom: 24px;">
            <h1 style="margin: 0; color: #111827; font-size: 24px; font-weight: 600;">
              Meeting Recap: ${payload.meetingTitle}
            </h1>
            <p style="margin: 8px 0 0 0; color: #6B7280; font-size: 14px;">
              ${payload.date}
            </p>
          </div>

          <!-- Executive Summary Section -->
          <div style="margin-bottom: 32px;">
            <h2 style="margin: 0 0 12px 0; color: #111827; font-size: 18px; font-weight: 600;">
              Executive Summary
            </h2>
            <div style="background-color: #F9FAFB; padding: 16px; border-radius: 8px; border-left: 4px solid #DC2626;">
              <p style="margin: 0; color: #374151; line-height: 1.7;">
                ${payload.summary}
              </p>
            </div>
          </div>

          <!-- Key Discussion Points Section -->
          <div style="margin-bottom: 32px;">
            <h2 style="margin: 0 0 12px 0; color: #111827; font-size: 18px; font-weight: 600;">
              Key Discussion Points
            </h2>
            ${keyDetailsHTML}
          </div>

          <!-- Footer -->
          <div style="border-top: 1px solid #E5E7EB; padding-top: 24px; margin-top: 32px; text-align: center;">
            <p style="margin: 0; color: #6B7280; font-size: 12px;">
              Generated by Qbot
            </p>
            <p style="margin: 8px 0 0 0; color: #9CA3AF; font-size: 11px;">
              The full transcript is attached to this email.
            </p>
          </div>
        </div>
      </body>
    </html>
  `;
}

/**
 * Send meeting recap email
 * @param payload - Meeting email payload with all required data
 * @returns Promise<{ success: boolean; error?: string }>
 */
export async function sendMeetingRecap(payload: MeetingEmailPayload): Promise<{ success: boolean; error?: string }> {
  try {
    const smtpFrom = process.env.SMTP_FROM || process.env.SMTP_USER;
    
    if (!smtpFrom) {
      throw new Error('SMTP_FROM not configured');
    }

    const transporter = createTransporter();

    // Generate HTML email body
    const htmlBody = generateEmailHTML(payload);

    // Convert transcript to buffer for attachment
    const transcriptBuffer = Buffer.from(payload.transcript, 'utf-8');

    // Send email
    const info = await transporter.sendMail({
      from: `"Qbot" <${smtpFrom}>`,
      to: payload.to,
      subject: `Meeting Recap: ${payload.meetingTitle}`,
      html: htmlBody,
      text: `
Meeting Recap: ${payload.meetingTitle}
Date: ${payload.date}

Executive Summary:
${payload.summary}

Key Discussion Points:
${payload.keyDetails.map((detail, idx) => `${idx + 1}. ${detail}`).join('\n')}

---
Generated by Qbot
Full transcript attached.
      `,
      attachments: [
        {
          filename: 'transcript.txt',
          content: transcriptBuffer,
          contentType: 'text/plain',
        },
      ],
    });

    logger.info('Meeting recap email sent successfully', {
      component: 'EmailService',
      to: payload.to,
      messageId: info.messageId,
    });

    return { success: true };
  } catch (error: any) {
    logger.error('Failed to send meeting recap email', error, {
      component: 'EmailService',
      to: payload.to,
      errorMessage: error.message,
    });

    return {
      success: false,
      error: error.message || 'Failed to send email',
    };
  }
}
